# Generated by Django 2.0 on 2018-01-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180117_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='num_of_items',
            new_name='item_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
